### ISSUE TITLE
The "+" button is not working in the project setion.

### ISSUE THREAD

**Issue by chandrasekhar2039** [EnigmaVSSUT/Qwik-Web#21]
In some project card, on hover we see + button which function is to expand the image to full screen -- The + button in the facebook clone is not working. and **do check for every project**.

**Comment by gouravdas3102** [comment]
Issue resolved of "+" button working of the projects  having the "+" button. and submitted pr

**Comment by chandrasekhar2039** [comment]
issue resolved by gourav
